import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Node.js ESM __dirname workaround
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const INPUT_FILE = path.join(__dirname, '../docs/mitre-reference.md');
const OUTPUT_FILE = path.join(__dirname, '../src/shared/config/mitre-index.ts');

const TACTIC_COLORS = {
    "reconnaissance": "#2dd4bf",         // Teal
    "resource-development": "#a3e635",   // Lime
    "initial-access": "#facc15",         // Yellow
    "execution": "#fb923c",              // Orange
    "persistence": "#c084fc",            // Purple
    "privilege-escalation": "#f87171",   // Light Red
    "defense-evasion": "#f472b6",        // Pink
    "credential-access": "#e879f9",      // Fuchsia
    "discovery": "#818cf8",              // Indigo
    "lateral-movement": "#60a5fa",       // Blue
    "collection": "#22d3ee",             // Cyan
    "command-and-control": "#34d399",    // Emerald
    "exfiltration": "#4ade80",           // Green
    "impact": "#fb7185"                  // Rose
};

const TACTIC_NAMES = {
    "reconnaissance": "Reconnaissance",
    "resource-development": "Resource Development",
    "initial-access": "Initial Access",
    "execution": "Execution",
    "persistence": "Persistence",
    "privilege-escalation": "Privilege Escalation",
    "defense-evasion": "Defense Evasion",
    "credential-access": "Credential Access",
    "discovery": "Discovery",
    "lateral-movement": "Lateral Movement",
    "collection": "Collection",
    "command-and-control": "Command and Control",
    "exfiltration": "Exfiltration",
    "impact": "Impact"
};

function main() {
    const content = fs.readFileSync(INPUT_FILE, 'utf-8');
    const lines = content.split('\n');

    const techniques = {};
    let currentTactic = "";

    // Parse Markdown
    for (const line of lines) {
        // Detect Tactic Header: "## RECONNAISSANCE ([RECONNAISSANCE])"
        const tacticMatch = line.match(/^## .* \(\[(.*)\]\)/);
        if (tacticMatch) {
            currentTactic = tacticMatch[1].toLowerCase();
            continue;
        }

        // Detect Table Row: "| `T1589` | [Gather Victim Identity Information](...) | ... |"
        if (line.trim().startsWith('| `T')) {
            const parts = line.split('|').map(s => s.trim()).filter(s => s !== '');
            if (parts.length >= 2) {
                const idRaw = parts[0].replace(/`/g, ''); // "T1589"
                const linkRaw = parts[1]; // "[Name](url)"

                const linkMatch = linkRaw.match(/\[(.*?)\]\((.*?)\)/);
                if (linkMatch) {
                    let name = linkMatch[1];
                    const url = linkMatch[2];
                    const isSubTechnique = name.includes('↳');

                    if (isSubTechnique) {
                        name = name.replace('↳', '').trim();
                    }

                    // If existing technique (multi-tactic), append tactic
                    if (techniques[idRaw]) {
                        if (!techniques[idRaw].tactics.includes(currentTactic)) {
                            techniques[idRaw].tactics.push(currentTactic);
                        }
                    } else {
                        // Create new technique
                        techniques[idRaw] = {
                            id: idRaw,
                            name: name,
                            url: url,
                            tactics: [currentTactic],
                            isSubTechnique: isSubTechnique,
                            // Assign primary color based on first tactic found
                            color: TACTIC_COLORS[currentTactic] || "#94a3b8"
                        };
                    }
                }
            }
        }
    }

    // Generate output file
    const outputContent = `/**
 * AUTO-GENERATED FILE
 * Source: docs/mitre-reference.md
 * Generated by: scripts/update_mitre_index.js
 */

export interface MitreTechnique {
    id: string;
    name: string;
    url: string;
    tactics: string[];
    isSubTechnique: boolean;
    color: string;
}

export const TACTIC_SLUGS: Record<string, string> = ${JSON.stringify(TACTIC_NAMES, null, 4)};

export const MITRE_INDEX: Record<string, MitreTechnique> = ${JSON.stringify(techniques, null, 4)};
`;

    fs.writeFileSync(OUTPUT_FILE, outputContent);
    console.log(`Generated ${Object.keys(techniques).length} techniques in ${OUTPUT_FILE}`);
}

main();
